a = input('Digite algo: ')
print('É alpha?', a.isalpha())
print('É númerico?', a.isnumeric())
print('É alphanúmerico?', a.isalnum())
print('É ASCII?', a.isascii())
print('É um digito?', a.isdigit())
print('É minusculo?', a.islower())
print('É maiusculo?', a.isupper())
print('É decimal?', a.isdecimal())
print('É identificador?', a.isidentifier())
print('É exibivel?', a.isprintable())
print('Tem espaço?', a.isspace())
print('É um titulo?', a.istitle())
